### ISSUE TITLE
Bootstrap sass not compiling into app.css

### ISSUE THREAD

**Issue by shenst1** [unionups/ember-cli-bootstrap-sass#15]
ember version: 0.2.3
node: 0.12.2
npm: 2.7.6

I ran the commands 
`ember new app`
`cd app`
`npm install --save-dev ember-cli-bootstrap-sass` 
`mv app/styles/app.css app/styles/app.scss`
add the line `@import: 'bootstrap';`
run
`ember serve`
When the app compiles, I get `dist/assets/app.scss` (rather than app.css) and all it contains is `@import: 'bootstrap';`. 
What am I missing?

```
"broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.3",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-bootstrap-sass": "^0.2.11",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.10",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.16.1",
    "ember-export-application-global": "^1.0.2"
```

http://stackoverflow.com/questions/29857506/ember-cli-bootstrap-sass-doesnt-compile-correctly

**Comment by dbouwman** [comment]
ember version: 1.13.7
node: 0.12.5
npm: 2.11.2

I ran into this as well - to save the next person from clicking on the SO link above - the solution seems to be to install `ember-cli-sass`

```
npm i --save-dev ember-cli-sass
``` 

However, once that was working I got errors in dev console:

![image](https://cloud.githubusercontent.com/assets/119129/9099175/e630225a-3b8b-11e5-9b2c-6658dc5929d4.png)

This is in a new ember-cli project following the steps specified by @shenst1 above.

**Comment by alejandrogutierrez** [comment]
@dbouwman I have the same issue.

**Comment by martinclavell** [comment]
lol few years later and same issue
